- name: Run Cypress Tests with Recording
  run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --parallel

- name: Upload Cypress Videos and Screenshots (if any)
  if: always()
  uses: actions/upload-artifact@4.3.1
  with:
    name: cypress-artifacts
    path: |
      cypress/videos
      cypress/screenshots
    retention-days: 7